En NumPy, los arrays son una estructura de datos fundamental que permite manejar y operar eficientemente con grandes conjuntos de datos numéricos. Uno de los aspectos clave de los arrays de NumPy es su capacidad para almacenar diferentes tipos de datos, lo que es esencial para el análisis y manipulación de datos. A continuación, se detalla cómo trabajar con arrays en NumPy y los diferentes tipos de datos que se pueden manejar.

# Consideraciones de Uso
### Memoria: 
Los tipos de datos más pequeños (uint8, int8, float16) consumen menos memoria, pero pueden no ser adecuados para todas las aplicaciones debido a sus limitaciones en el rango y la precisión.
### Precisión 
Para aplicaciones científicas y de ingeniería, se suelen usar tipos de datos de mayor precisión como float64 y complex128.
### Compatibilidad: 
Asegúrate de elegir el tipo de dato adecuado para la compatibilidad con otras librerías y herramientas que utilices.
Seleccionar el tipo de dato adecuado es crucial para optimizar el rendimiento y la eficiencia de tus operaciones en NumPy.

In [1]:
import numpy as np

# Crear arrays con diferentes tipos de datos
array_int = np.array([1, 2, 3], dtype=np.int32)
array_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
array_complex = np.array([1+2j, 3+4j], dtype=np.complex128)
array_bool = np.array([True, False, True], dtype=np.bool_)
array_str = np.array(['a', 'b', 'c'], dtype='<U1')
array_obj = np.array([1, "a", 3.0], dtype=object)

# Verificación de tipos de datos
print(f"array_int: {array_int}, dtype: {array_int.dtype}")
print(f"array_float: {array_float}, dtype: {array_float.dtype}")
print(f"array_complex: {array_complex}, dtype: {array_complex.dtype}")
print(f"array_bool: {array_bool}, dtype: {array_bool.dtype}")
print(f"array_str: {array_str}, dtype: {array_str.dtype}")
print(f"array_obj: {array_obj}, dtype: {array_obj.dtype}")

# Conversión de tipos de datos
array_int_a_float = array_int.astype(np.float64)
print(f"array_int convertido a float: {array_int_a_float}, dtype: {array_int_a_float.dtype}")

# Funciones de inicialización
array_zeros = np.zeros((2, 2))
array_ones = np.ones((2, 2))
array_empty = np.empty((2, 2))
array_arange = np.arange(0, 10, 2)
array_linspace = np.linspace(0, 1, 5)
array_identity = np.eye(3)
array_diagonal = np.diag([1, 2, 3])

print(f"array_zeros:\n{array_zeros}")
print(f"array_ones:\n{array_ones}")
print(f"array_empty:\n{array_empty}")
print(f"array_arange:\n{array_arange}")
print(f"array_linspace:\n{array_linspace}")
print(f"array_identity:\n{array_identity}")
print(f"array_diagonal:\n{array_diagonal}")


array_int: [1 2 3], dtype: int32
array_float: [1. 2. 3.], dtype: float64
array_complex: [1.+2.j 3.+4.j], dtype: complex128
array_bool: [ True False  True], dtype: bool
array_str: ['a' 'b' 'c'], dtype: <U1
array_obj: [1 'a' 3.0], dtype: object
array_int convertido a float: [1. 2. 3.], dtype: float64
array_zeros:
[[0. 0.]
 [0. 0.]]
array_ones:
[[1. 1.]
 [1. 1.]]
array_empty:
[[6.93079524e-310 4.66570084e-310]
 [6.93079417e-310 6.93079417e-310]]
array_arange:
[0 2 4 6 8]
array_linspace:
[0.   0.25 0.5  0.75 1.  ]
array_identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
array_diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


#### Tipos de Datos en NumPy
Enteros Sin Signo (uint)

- uint8: Entero sin signo de 8 bits, rango de 0 a 255.
- uint16: Entero sin signo de 16 bits, rango de 0 a 65,535.
- uint32: Entero sin signo de 32 bits, rango de 0 a 4,294,967,295.
- uint64: Entero sin signo de 64 bits, rango de 0 a 18,446,744,073,709,551,615.

Enteros con Signo (int)

- int8: Entero con signo de 8 bits, rango de -128 a 127.
- int16: Entero con signo de 16 bits, rango de -32,768 a 32,767.
- int32: Entero con signo de 32 bits, rango de -2,147,483,648 a 2,147,483,647.
- int64: Entero con signo de 64 bits, rango de -9,223,372,036,854,775,808 a 9,223,372,036,854,775,807.

Flotantes (float)

- float16: Flotante de 16 bits, precisión baja.
- float32: Flotante de 32 bits, precisión simple.
- float64: Flotante de 64 bits, precisión doble (este es el tipo de flotante por defecto en NumPy).

Complejos (complex)

- complex64: Número complejo de 64 bits (32 bits para la parte real y 32 bits para la parte imaginaria).
- complex128: Número complejo de 128 bits (64 bits para la parte real y 64 bits para la parte imaginaria, este es el tipo de complejo por defecto en NumPy).

In [2]:
import numpy as np

# Enteros sin signo
array_uint8 = np.array([0, 255], dtype=np.uint8)
print(array_uint8, array_uint8.dtype)

# Enteros con signo
array_int8 = np.array([-128, 127], dtype=np.int8)
print(array_int8, array_int8.dtype)

# Flotantes
array_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(array_float64, array_float64.dtype)

# Complejos
array_complex128 = np.array([1+2j, 3+4j], dtype=np.complex128)
print(array_complex128, array_complex128.dtype)

# Booleanos
array_bool = np.array([True, False, True], dtype=np.bool_)
print(array_bool, array_bool.dtype)

# Cadenas de caracteres
array_str = np.array(['a', 'bc', 'def'], dtype='<U3')
print(array_str, array_str.dtype)

# Objetos
array_obj = np.array([1, "a", 3.0], dtype=object)
print(array_obj, array_obj.dtype)


[  0 255] uint8
[-128  127] int8
[1. 2. 3.] float64
[1.+2.j 3.+4.j] complex128
[ True False  True] bool
['a' 'bc' 'def'] <U3
[1 'a' 3.0] object
