In [2]:
import numpy as np

# Paso 1: Crear un array de 100 números
array = np.arange(100)
print("Array original:", array)

# Paso 2: Broadcasting
small_array = np.array([1, 2, 3, 4, 5])
broadcast_result = array.reshape(20, 5) + small_array
print("Resultado de Broadcasting:\n", broadcast_result)

# Paso 3: Operaciones Lógicas
mask = array > 50
selected_elements = array[mask]
print("Elementos mayores a 50:", selected_elements)

# Paso 4: Combinación de Broadcasting y Operaciones Lógicas
broadcast_mask = broadcast_result > 55
selected_broadcast_elements = broadcast_result[broadcast_mask]
print("Elementos mayores a 55 después de Broadcasting:", selected_broadcast_elements)


Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Resultado de Broadcasting:
 [[  1   3   5   7   9]
 [  6   8  10  12  14]
 [ 11  13  15  17  19]
 [ 16  18  20  22  24]
 [ 21  23  25  27  29]
 [ 26  28  30  32  34]
 [ 31  33  35  37  39]
 [ 36  38  40  42  44]
 [ 41  43  45  47  49]
 [ 46  48  50  52  54]
 [ 51  53  55  57  59]
 [ 56  58  60  62  64]
 [ 61  63  65  67  69]
 [ 66  68  70  72  74]
 [ 71  73  75  77  79]
 [ 76  78  80  82  84]
 [ 81  83  85  87  89]
 [ 86  88  90  92  94]
 [ 91  93  95  97  99]
 [ 96  98 100 102 104]]
Elementos mayores a 50: [51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]
Elementos mayo

## Explicación
- Creación del Array: Se crea un array de 100 números (del 0 al 99).
- Broadcasting: Se suma un array más pequeño (small_array) a bloques de 5 elementos del array original. Se utiliza reshape para - organizar el array original en bloques de 5 elementos.
- Operaciones Lógicas: Se crea una máscara booleana para seleccionar elementos mayores a 50 del array original.
- Combinación: Se crea una máscara booleana para seleccionar elementos del resultado del broadcasting que son mayores a 55.