In [1]:
import numpy as np

# Creación de matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8], [9, 10]])
E = np.array([[1, 2], [3, 4]])

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)

# Suma y Resta
suma = A + B
resta = A - B
print("\nSuma de A y B:")
print(suma)
print("\nResta de A y B:")
print(resta)

# Multiplicación elemento a elemento
multiplicacion_elemento = A * B
print("\nMultiplicación elemento a elemento de A y B:")
print(multiplicacion_elemento)

# Producto punto
producto_punto = np.dot(C, D)
print("\nProducto punto de C y D:")
print(producto_punto)

# Transposición
A_transpuesta = A.T
print("\nTransposición de A:")
print(A_transpuesta)

# Inversión y Determinante
E_inversa = np.linalg.inv(E)
determinante_E = np.linalg.det(E)
print("\nInversa de E:")
print(E_inversa)
print("\nDeterminante de E:")
print(determinante_E)

# Eigenvalores y Eigenvectores
eigenvalores, eigenvectores = np.linalg.eig(E)
print("\nEigenvalores de E:")
print(eigenvalores)
print("\nEigenvectores de E:")
print(eigenvectores)

# Solución de sistemas de ecuaciones lineales
A_sys = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A_sys, b)
print("\nSolución del sistema de ecuaciones Ax = b:")
print(x)

# Normas de matrices
norma_A = np.linalg.norm(A)
print("\nNorma de A:")
print(norma_A)


Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Suma de A y B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Resta de A y B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplicación elemento a elemento de A y B:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Producto punto de C y D:
[[ 25  28]
 [ 57  64]
 [ 89 100]]

Transposición de A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Inversa de E:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinante de E:
-2.0000000000000004

Eigenvalores de E:
[-0.37228132  5.37228132]

Eigenvectores de E:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Solución del sistema de ecuaciones Ax = b:
[2. 3.]

Norma de A:
16.881943016134134
