In [1]:
import numpy as np
import pandas as pd

In [2]:
# Crear un array original
original_array = np.array([1, 2, 3, 4, 5])

# Crear una vista del array original
view_array = original_array[1:4]

# Crear una copia del array original
copy_array = original_array[1:4].copy()

# Modificar la vista
view_array[0] = 99

print("Array original después de modificar la vista:", original_array)
print("Vista del array:", view_array)

# Modificar la copia
copy_array[0] = 77

print("Array original después de modificar la copia:", original_array)
print("Copia del array:", copy_array)


Array original después de modificar la vista: [ 1 99  3  4  5]
Vista del array: [99  3  4]
Array original después de modificar la copia: [ 1 99  3  4  5]
Copia del array: [77  3  4]


## Copias y Vistas en un Array 2D

In [3]:
# Crear un array 2D original
original_array_2d = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])

# Crear una vista del array 2D original
view_array_2d = original_array_2d[:2, 1:]

# Crear una copia del array 2D original
copy_array_2d = original_array_2d[:2, 1:].copy()

# Modificar la vista
view_array_2d[0, 0] = 99

print("Array 2D original después de modificar la vista:\n", original_array_2d)
print("Vista del array 2D:\n", view_array_2d)

# Modificar la copia
copy_array_2d[0, 0] = 77

print("Array 2D original después de modificar la copia:\n", original_array_2d)
print("Copia del array 2D:\n", copy_array_2d)


Array 2D original después de modificar la vista:
 [[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]
Vista del array 2D:
 [[99  3]
 [ 5  6]]
Array 2D original después de modificar la copia:
 [[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]
Copia del array 2D:
 [[77  3]
 [ 5  6]]


## Elementos Únicos y Conteos: 
- Utiliza np.unique para encontrar elementos únicos y sus conteos en arrays unidimensionales y multidimensionales.
## Copias y Vistas: 
- Las vistas son referencias al mismo bloque de memoria que el array original, mientras que las copias son réplicas independientes. Cambios en una vista afectan al array original, pero cambios en una copia no.
- Estas herramientas son útiles para trabajar con datos en NumPy de manera eficiente y flexible.