- Ejemplos de transformación de arrays usando reshape y otras manipulaciones comunes en NumPy. Este script incluye ejemplos de cómo crear arrays, remodelarlos y realizar varias manipulaciones útiles.

## Transformación de Arrays y Manipulación

In [1]:
import numpy as np

# Crear un array de 1 a 120
array = np.arange(1, 121)
print("Array original:")
print(array)

# Remodelar el array a (10, 12)
reshaped_array_1 = array.reshape(10, 12)
print("\nArray remodelado a (10, 12):")
print(reshaped_array_1)

# Remodelar el array a (4, 30)
reshaped_array_2 = array.reshape(4, 30)
print("\nArray remodelado a (4, 30):")
print(reshaped_array_2)

# Remodelar el array a (6, 20)
reshaped_array_3 = array.reshape(6, 20)
print("\nArray remodelado a (6, 20):")
print(reshaped_array_3)

# Remodelar el array a (3, 40)
reshaped_array_4 = array.reshape(3, 40)
print("\nArray remodelado a (3, 40):")
print(reshaped_array_4)

# Transponer el array remodelado (6, 20)
transposed_array = reshaped_array_3.T
print("\nArray transpuesto de (6, 20):")
print(transposed_array)

# Aplanar el array transpuesto de vuelta a 1D
flattened_array = transposed_array.flatten()
print("\nArray transpuesto aplanado de vuelta a 1D:")
print(flattened_array)

# Crear un array 2D y obtener una vista y una copia
original_array_2d = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
print("\nArray 2D original:")
print(original_array_2d)

# Vista del array original
view_array_2d = original_array_2d[:2, 1:]
print("\nVista del array 2D original:")
print(view_array_2d)

# Copia del array original
copy_array_2d = original_array_2d[:2, 1:].copy()
print("\nCopia del array 2D original:")
print(copy_array_2d)

# Modificar la vista y la copia
view_array_2d[0, 0] = 99
copy_array_2d[0, 0] = 77

print("\nArray 2D original después de modificar la vista:")
print(original_array_2d)
print("Vista del array 2D modificada:")
print(view_array_2d)
print("Copia del array 2D modificada:")
print(copy_array_2d)

# Obtener elementos únicos y sus conteos en un array 1D
array_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_elements, counts = np.unique(array_with_duplicates, return_counts=True)
print("\nElementos únicos en array 1D con duplicados:")
print("Elementos únicos:", unique_elements)
print("Conteos:", counts)

# Obtener elementos únicos y sus conteos en un array 2D
array_2d_with_duplicates = np.array([[1, 2, 3],
                                     [4, 5, 6],
                                     [1, 2, 3]])
unique_elements_2d, counts_2d = np.unique(array_2d_with_duplicates, return_counts=True)
print("\nElementos únicos en array 2D con duplicados:")
print("Elementos únicos:", unique_elements_2d)
print("Conteos:", counts_2d)


Array original:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120]

Array remodelado a (10, 12):
[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [ 13  14  15  16  17  18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34  35  36]
 [ 37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72]
 [ 73  74  75  76  77  78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108]
 [109 1


### Creación y Remodelación de Arrays:

- Se crea un array de 1 a 120 usando np.arange(1, 121).
- Se remodela el array a diferentes formas compatibles: (10, 12), (4, 30), (6, 20), y (3, 40).
### Transposición y Aplanado:

- Se transpone un array remodelado de (6, 20) a (20, 6) usando .T.
- Se aplana el array transpuesto de vuelta a 1D usando .flatten().
### Vistas y Copias:

- Se crea un array 2D y se obtiene una vista y una copia de un segmento del array.
- Se modifica la vista y la copia para demostrar cómo las modificaciones afectan al array original y las diferencias entre vistas y copias.
### Elementos Únicos y Conteos:

- Se utiliza np.unique para obtener elementos únicos y sus conteos en un array 1D con duplicados.
- Se repite el proceso para un array 2D.


#### Este script proporciona una visión completa de cómo trabajar con arrays en NumPy, incluyendo remodelación, transposición, vistas, copias y operaciones con elementos únicos.






