In [1]:
import numpy as np 

In [2]:
escalar = np.array(84)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
84


Vectores Dimension uno 

In [3]:
vector = np.array([30,32,12,56,78,90,43,67,89,29,12,30,76,80,100])
print(type(vector))
print(vector)

<class 'numpy.ndarray'>
[30.  32.  12.  56.  78.  90.  43.  67.  89.  29.  12.  30.  76.  80.1]


Matrices Mas de dos dimencioneds 

In [4]:
matrix = np.array([[32,45,67],[21,65,90],[53,65,38]])
print(matrix)

[[32 45 67]
 [21 65 90]
 [53 65 38]]


tensor mas de cuatro dimenciones 

In [5]:
tensor = np.array([[[2,4,5,6],[8,9,2,4],[1,3,6,9],[2,4,7,8]]])
print(tensor)

[[[2 4 5 6]
  [8 9 2 4]
  [1 3 6 9]
  [2 4 7 8]]]


Creando rrangos con numpy

In [7]:
array_arange = np.arange(101)
print(array_arange)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [8]:
# Matrix identidad 
eye_matrix = np.eye(10)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
# Matrix Diagonal 
diag_matrix = np.diag([1,2,3,4,5,6,7,8,9])
print(diag_matrix)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [12]:
#Usos de random con numpy
random = np.random.random((4,6))
print(random)

[[0.13854545 0.83850242 0.25393813 0.71384026 0.21138088 0.47052053]
 [0.37174494 0.43588634 0.40271895 0.02441231 0.07279389 0.87693113]
 [0.89275654 0.91407487 0.50506088 0.09998224 0.22421018 0.63433562]
 [0.8593493  0.52270897 0.97231024 0.33301954 0.57813138 0.91288019]]


In [13]:
import numpy as np
import pandas as pd

# NumPy: Escalar, Vector, Matriz, Tensor
escalar = np.array(5)
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"Escalar: {escalar}, Dimensiones: {escalar.ndim}")
print(f"Vector: {vector}, Dimensiones: {vector.ndim}, Forma: {vector.shape}")
print(f"Matriz: {matriz}, Dimensiones: {matriz.ndim}, Forma: {matriz.shape}")
print(f"Tensor: {tensor}, Dimensiones: {tensor.ndim}, Forma: {tensor.shape}")

# Pandas: Serie y DataFrame
serie = pd.Series([1, 2, 3])
dataframe = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

print(f"Serie:\n{serie}\nForma: {serie.shape}")
print(f"DataFrame:\n{dataframe}\nForma: {dataframe.shape}")


Escalar: 5, Dimensiones: 0
Vector: [1 2 3], Dimensiones: 1, Forma: (3,)
Matriz: [[1 2 3]
 [4 5 6]], Dimensiones: 2, Forma: (2, 3)
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], Dimensiones: 3, Forma: (2, 2, 2)
Serie:
0    1
1    2
2    3
dtype: int64
Forma: (3,)
DataFrame:
   A  B
0  1  4
1  2  5
2  3  6
Forma: (3, 2)
