In [1]:
import numpy as np
import pandas as pd 

In [3]:
array = np.array([[3,4,5,7], [1,2,3,4],[7,8,9,0]])
print(array.ndim)
print(array.shape)
print(array.dtype)
print(array)

2
(3, 4)
int64
[[3 4 5 7]
 [1 2 3 4]
 [7 8 9 0]]


In [5]:
z = np.array(3, dtype=np.uint8)
print(z)

3


In [6]:
double_array = np.array([1,2,3,4], dtype='d')
print(double_array)

[1. 2. 3. 4.]


In [7]:
z = z.astype(np.float64)
print(z)

3.0


In [9]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
add = np.sum(array)
print(array)
print(add)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]
48


In [10]:
array = np.array([[3,4,5,7], [1,2,3,4],[7,8,9,0]])

In [11]:
mean = np.mean(array)
print(mean)

4.416666666666667


In [12]:
std = np.std(array)
print(std)

2.722080495176846


In [13]:
import numpy as np

# Enteros sin signo
array_uint8 = np.array([0, 255], dtype=np.uint8)
print(array_uint8, array_uint8.dtype)

# Enteros con signo
array_int8 = np.array([-128, 127], dtype=np.int8)
print(array_int8, array_int8.dtype)

# Flotantes
array_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(array_float64, array_float64.dtype)

# Complejos
array_complex128 = np.array([1+2j, 3+4j], dtype=np.complex128)
print(array_complex128, array_complex128.dtype)

# Booleanos
array_bool = np.array([True, False, True], dtype=np.bool_)
print(array_bool, array_bool.dtype)

# Cadenas de caracteres
array_str = np.array(['a', 'bc', 'def'], dtype='<U3')
print(array_str, array_str.dtype)

# Objetos
array_obj = np.array([1, "a", 3.0], dtype=object)
print(array_obj, array_obj.dtype)


[  0 255] uint8
[-128  127] int8
[1. 2. 3.] float64
[1.+2.j 3.+4.j] complex128
[ True False  True] bool
['a' 'bc' 'def'] <U3
[1 'a' 3.0] object


## Consideraciones de Uso
- Memoria: 
Los tipos de datos más pequeños (uint8, int8, float16) consumen menos memoria, pero pueden no ser adecuados para todas las aplicaciones debido a sus limitaciones en el rango y la precisión.
- Precisión: 
Para aplicaciones científicas y de ingeniería, se suelen usar tipos de datos de mayor precisión como float64 y complex128.
- Compatibilidad: 
Asegúrate de elegir el tipo de dato adecuado para la compatibilidad con otras librerías y herramientas que utilices.
Seleccionar el tipo de dato adecuado es crucial para optimizar el rendimiento y la eficiencia de tus operaciones en NumPy.