- El broadcasting y las operaciones lógicas en NumPy son características muy útiles que permiten realizar operaciones eficientes y expresivas en arrays. A continuación, te explico ambos conceptos y cómo usarlos con ejemplos.

# Broadcasting en NumPy
El broadcasting es una técnica que permite realizar operaciones aritméticas en arrays de diferentes formas (shapes). NumPy automáticamente "extiende" el array más pequeño para que coincida con la forma del array más grande, sin hacer copias de datos.


In [2]:
import numpy as np 
import pandas as pd

Aplicando descuentos a congunto de precios en el array 

In [3]:
prices = np.array([100,200,300,400,500,600])
discount = np.array([0.9])
discount_prices = prices * discount
print(prices)
print(discount_prices)

[100 200 300 400 500 600]
[ 90. 180. 270. 360. 450. 540.]


In [4]:
prices = np.random.randint(100,2000, size=(6,6))
discount = np.array([10,20,30,40,50,60])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[1488  767 1259  879 1728 1859]
 [ 668 1144  323 1455 1093 1047]
 [1081  544 1738  153 1894  822]
 [ 100 1510  234  956  147 1604]
 [ 190 1047 1104  869  661 1079]
 [1136  102  834 1925 1553 1103]]
[[1498  787 1289  919 1778 1919]
 [ 678 1164  353 1495 1143 1107]
 [1091  564 1768  193 1944  882]
 [ 110 1530  264  996  197 1664]
 [ 200 1067 1134  909  711 1139]
 [1146  122  864 1965 1603 1163]]


In [5]:
prices = np.random.randint(100,2000, size=(6,6))
discount = np.array([10,20,30,40,50,60])
discount_prices = prices * discount
print(prices)
print(discount_prices)

[[1986 1258 1893  903  271 1450]
 [1559  215 1015  920  918  839]
 [ 857  626  837  528 1248 1726]
 [1565 1735 1217  772 1903 1481]
 [1832  193 1180 1564 1934  119]
 [ 757 1583 1482  904  217 1268]]
[[ 19860  25160  56790  36120  13550  87000]
 [ 15590   4300  30450  36800  45900  50340]
 [  8570  12520  25110  21120  62400 103560]
 [ 15650  34700  36510  30880  95150  88860]
 [ 18320   3860  35400  62560  96700   7140]
 [  7570  31660  44460  36160  10850  76080]]


Operaciones logicas con  numpy

In [6]:
array = np.array([1,2,3,4,5,6,7,8,9])
print(np.all(array > 0))
array = np.array([1,2,3,4,5,6,7,8,9])
print(np.all(array < 0))

True
False


In [7]:
#Trabajando con el metodo any
print(np.any(array > 4))
print(np.any(array > 9))
print(np.any(array > 11))
print(np.any(array > 0))

True
False
False
True


In [8]:
#concatenaciones de arrays 
array_a =  np.array([1,2,3,4,5,6,7,8,9,10])
array_b = ([11,12,13,14,15,16,17,18,19,20])
concatenate = np.concatenate((array_a, array_b))
print(array_a)
print(array_b)
print(concatenate)

[ 1  2  3  4  5  6  7  8  9 10]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
#concatenaciones de arrays 
array_a =  np.array([1,2,3,4,5,6,7,8,9,10])
array_b = ([11,12,13,14,15,16,17,18,19,20])
concatenate_a = np.concatenate((array_a, array_a))
concatenate_b = np.concatenate((array_a, array_b))
print(array_a)
print(array_b)
print(concatenate_a)
print(concatenate_b)

[ 1  2  3  4  5  6  7  8  9 10]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
#staquiando vertical y orizantalmente 
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [12]:
#staquiando vertical y orizantalmente 
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
# Dividiendo rangos de arrays con split
array_c = np.arange(1,100)
split_array = np.split(array_c,3)
print(array_c)
print(split_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]), array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]), array([67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]
