## Elementos Unicos

### Copias y Vistas
- En NumPy, una copia es una réplica independiente del array original, mientras que una vista es una referencia al mismo bloque de memoria. Cambios en una vista se reflejarán en el array original, mientras que los cambios en una copia no afectarán al array original.

In [6]:
import numpy as np
import pandas as pd

In [7]:
survey_responses = np.array(['bueno', 'excelente', 'malo',
                            'bueno', 'malo', 'excelente',
                            'bueno', 'bueno', 'malo'
                            'excelente', 'bueno', 'excelente', 
                            'malo', 'malo', 'excelente',
                            'bueno', 'malo', 'excelente',
                            'bueno', 'bueno', 'malo',
                            'excelente'])

print(np.unique(survey_responses))

['bueno' 'excelente' 'malo' 'maloexcelente']


In [8]:
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo' 'maloexcelente']
[8 6 6 1]


Modificando arrays 

In [24]:
array_x = np.arange(101)
view_y = array_x[10:20]
print(array_x)
print(view_y)
array_x[1:3] = [101,121]
print(array_x)
print(view_y)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[10 11 12 13 14 15 16 17 18 19]
[  0 101 121   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[10 11 12 13 14 15 16 17 18 19]


In [26]:
array_x = np.arange(101)
copy_x = array_x[[10,20]]
print(array_x)
print(copy_x)
array_x[1:3] = [101,121]
print(array_x)
print(copy_x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[10 20]
[  0 101 121   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[10 20]


In [20]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)
array_x[1:3] = [10,11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [19]:
import numpy as np

# Crear un array original
array_x = np.arange(50)
print("Array original:", array_x)

# Crear una vista del array original
view_y = array_x[10:30]
print("Vista del array original:", view_y)

# Asignar un array de tamaño compatible (20 elementos) a la sección [10:30] del array original
array_x[10:30] = np.arange(101, 121)
print("Array original después de la asignación:", array_x)
print("Vista del array después de la asignación:", view_y)

# Crear una copia del array original
copy_z = array_x[10:30].copy()
print("Copia del array original:", copy_z)

# Modificar la copia
copy_z[0] = 999
print("Copia modificada:", copy_z)
print("Array original después de modificar la copia:", array_x)
print("Vista del array después de modificar la copia:", view_y)


Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Vista del array original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Array original después de la asignación: [  0   1   2   3   4   5   6   7   8   9 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49]
Vista del array después de la asignación: [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]
Copia del array original: [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]
Copia modificada: [999 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]
Array original después de modificar la copia: [  0   1   2   3   4   5   6   7   8   9 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 11