In [1]:
import numpy as np 
import pandas as pd

In [2]:
A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[9,10,11,12],[12,13,14,15]])
sum = A + B
print(A)
print(B)
print(sum)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [12 13 14 15]]
[[10 12 14 16]
 [17 19 21 23]]


In [7]:
# Multiplicacion
B_transpuesta = B.T
producto = np.dot(A, B_transpuesta)
print("Producto punto de A y B_transpuesta:")
print(producto)

Producto punto de A y B_transpuesta:
[[110 140]
 [278 356]]


In [9]:
# Determinante 
A = np.array([[1,2],[5,6]])
B = np.array([[9,10],[12,13]])
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
inv_A = np.linalg.inv(A)
inv_B = np.linalg.inv(B)
print(A)
print(B)
print(det_A)
print(det_B)
print(inv_A)
print(inv_B)

[[1 2]
 [5 6]]
[[ 9 10]
 [12 13]]
-3.999999999999999
-3.0000000000000004
[[-1.5   0.5 ]
 [ 1.25 -0.25]]
[[-4.33333333  3.33333333]
 [ 4.         -3.        ]]


In [10]:
# resolver Ax = b
b = np.array([10,12])
x = np.linalg.solve(A,b)
print(x)

[-9.   9.5]
