In [1]:
import numpy as np 
import pandas as pd 

Coleciones de arrays 

In [6]:
array = np.array([10,20,30,40,50,60,70,80,90,100])
print(array[1])
print(array[-1])
print(array[1:5])
print(array[1:7])
print(array[7:-1])
print(array[-1:-7])

20
100
[20 30 40 50]
[20 30 40 50 60 70]
[80 90]
[]


Indexación Booleana

In [8]:
array = np.array([10,20,30,40,50,60,70,80,90,100])
bool_index = array > 35
print(type(bool_index))
print(bool_index)
print(array)

<class 'numpy.ndarray'>
[False False False  True  True  True  True  True  True  True]
[ 10  20  30  40  50  60  70  80  90 100]


Array de mulples dimenciones 


In [12]:
index = [2,4,6,2,9,0,3,3,1]
print(array[index])

[ 30  50  70  30 100  10  40  40  20]


In [18]:
# Numeros aleatoruios 
array = np.random.randint(1,100, size=(4,4))
print(array)
print(array[3,2])

[[56 75 33 33]
 [78 26 24  3]
 [55 93 33 80]
 [34 37 81  6]]
81


In [19]:
print(array[:2:3])

[[56 75 33 33]]


## Resumen
- Indexación Básica: Acceso a elementos individuales con índices enteros.
- Indexación con Listas y Booleana: Selección de múltiples elementos utilizando listas de índices o máscaras booleanas.
- Slicing: Selección de subarrays con notación de dos puntos, incluyendo pasos.
- Indexación en Arrays Multidimensionales: Aplicación de slicing y selección en cada dimensión.
- Indexación Avanzada: Selección de elementos arbitrarios utilizando arrays de índices y combinaciones de métodos.