En NumPy, la transformación y manipulación de arrays es una tarea común y útil para muchas operaciones de análisis de datos. Vamos a explorar cómo usar las funciones reshape y otras técnicas de manipulación para trabajar con arrays de manera efectiva.

In [2]:
import numpy as np

In [4]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
transponse_matrix = matrix.T
print(matrix)
print('Matrix Trspueta')
print(transponse_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Matrix Trspueta
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [9]:
# Reshaped
array = np.arange(1,121)
reshaped_array = array.reshape(10,12)
print(array)
print(reshaped_array)

#Al manejar estas reshaped debemos tener en cueta las dimencionalidades para no tener errores 
# si tenemos un array con un rando de 1 a 120 debemos manejar un array con dimenciones 10 * 12

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120]
[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [ 13  14  15  16  17  18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34  35  36]
 [ 37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72]
 [ 73  74  75  76  77  78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116 117 118 119 120]]


In [10]:
# modificando los array
reversed_array = array[::-1]
print(array)
print(reversed_array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120]
[120 119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103
 102 101 100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85
  84  83  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67
  66  65  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49
  48  47  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31
  30  29  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13
  12  11  10   9   8   7   6   5   4   3   2   1]


Flatting convierte un array multidimencionel en un array udimencional 

In [11]:
# Aplanando matrices 
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
flatened_array = matrix.flatten()
print(matrix)
print(flatened_array)

# aplanar array es muy util en deep learnig cuando queremos aplanar una imegen y queremos pasarla 
# a cada una de las neurones de la red neuronal 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
